export { default as clearConsole } from './clearConsole'
export { default as openBrowser } from './openBrowser'
export { default as getConfig, getSysConfig } from './getConfig'
export { default as logExit } from './logExit'
export { spawn, spawnSync, spawnSyncEx } from './spawn'
export { exec, execSync, execSyncEx } from './exec'
export { default as extend } from './extend'

export { default as chalk } from 'chalk'
export { default as fs } from 'fs-extra'
